import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/toaster"

const interClassName = "font-inter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <style>{`
          .${interClassName} {
            font-family: 'Inter', sans-serif;
          }
        `}</style>
      </head>
      <body className={interClassName}>
        <div className="relative flex flex-col justify-center items-center ">
          <Navbar />
        </div>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
